# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda63a99c85720c16c11ee17983113f2716186763c8645df094cf2472651aacf0af44af513f53575bb46f65af9dd24b45466d23c9e2b46e884871735b51a7eb8

test:
  secret_key_base: f6a41a557dd766727f683c27cd976e4ece75462259e6c058f8a64162b3a166d9c7d6bcc9652d713c4e4d8dfbdd5b968f496e50a2f1df0ff5deac1f40747d9f4b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
